### ISSUE TITLE
Error finding vulnerable folders

### ISSUE THREAD

**Issue by benichmt1** [itm4n/Ikeext-Privesc#1]
Hello,
It looks like in https://github.com/itm4n/Ikeext-Privesc/blob/master/Ikeext-Privesc.ps1#L491-#L492 the check is passing the exploit an array of vulnerable folders. The issue is that the PassThru command doesn't properly initialize this if there is a single vulnerable folder in the path.

For example, running 
`$vuln_folder = Invoke-IkeextCheck -PassThru` with a single folder and checking on that variable will give you

`C:\Folder`.

As a result, the check in https://github.com/itm4n/Ikeext-Privesc/blob/master/Ikeext-Privesc.ps1#L498 fails and https://github.com/itm4n/Ikeext-Privesc/blob/master/Ikeext-Privesc.ps1#L504 produces a single character "C", not the first element of the array.

Bypassing these checks manually worked for me. Let me know if you want me to make a PR or you want to handle it some other way.

**Comment by itm4n** [comment]
Hello, 
Thanks for your message and the clear description of the issue. I was able to quickly reproduce it. 

I solved this by casting the `$vulnerable_folders` variable in the exploit code.

```powershell
[String[]]$vulnerable_folders = Invoke-IkeextCheck -PassThru 
```
Therefore, if only `C:\Folder` is vulnerable, `$vulnerable_folders[0]` will now yield `C:\Folder` rather than just the first character of the string. It tested it successfully on my Windows 7 VM.

It's probably not the best way to do it but since the `-PassThru` option was not intended to be used outside of this script, I guess it will do the trick...
